<?php

namespace ForumBundle\Repository;

/**
 * ForumThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumThemeRepository extends \Doctrine\ORM\EntityRepository
{

	public function getCountAnswers($theme_id)
	{
		$sql = "

		SELECT COUNT(*) count
		FROM `forum_theme` 
		left join forum_message on forum_message.forum_theme_id = `forum_theme`.id
		WHERE `forum_theme`.`id` = ".$theme_id." and `forum_theme`.`closed` = 0 and `forum_theme`.`active` = 1
		and forum_message.active = 1 
		and forum_message.moderation = 1

		";	
		$connection = $this->_em->getConnection();
		$statement = $connection->prepare($sql);
		$statement->execute();
		$result = $statement->fetchColumn();
		
		return $result;
	}	
	
}
