<?php

namespace ForumBundle\Repository;

/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function getCountThemes($forum_id)
	{
		$sql = "
		select count(*) count
		from 
		(
		SELECT `forum_theme`.id  as ids
		FROM `forum_theme` 
		left join forum_message on forum_message.forum_theme_id = `forum_theme`.id
		WHERE `forum_theme`.`forum_id` = ".$forum_id." and `forum_theme`.`closed` = 0 and `forum_theme`.`active` = 1
		and forum_message.active = 1 
		and forum_message.moderation = 1
		and forum_message.block = 0
		group by `forum_theme`.id 
		) as table_1
		";	
		$connection = $this->_em->getConnection();
		$statement = $connection->prepare($sql);
		$statement->execute();
		$result = $statement->fetchColumn();
		
		return $result;
	}	
	public function getCountAnswers($forum_id)
	{
		$sql = "
		select sum(count) count
		from 
		(
		SELECT COUNT(*) count
		FROM `forum_theme` 
		left join forum_message on forum_message.forum_theme_id = `forum_theme`.id
		WHERE `forum_theme`.`forum_id` = ".$forum_id." and `forum_theme`.`closed` = 0 and `forum_theme`.`active` = 1
		and forum_message.active = 1 
		and forum_message.moderation = 1
		group by `forum_theme`.id 
		) as table_1
		";	
		$connection = $this->_em->getConnection();
		$statement = $connection->prepare($sql);
		$statement->execute();
		$result = $statement->fetchColumn();
		
		return $result;
	}	
	public function getLastMessage($forum_id)
	{
		$sql = "
		SELECT ft,u
		FROM ForumBundle\Entity\ForumTheme ft
		LEFT JOIN ft.forumMessages fm
		LEFT JOIN ft.user  u
		WHERE ft.forum = ".$forum_id." 
		and ft.closed = 0 
		and ft.active = 1
		and fm.active = 1 
		and fm.moderation = 1
        order by  fm.datetime desc
		";	
   		$q = $this->_em->createQuery($sql)->setMaxResults(1);
   		return $q->getOneOrNullResult();
	}
}


