<?php

namespace BaseBundle\Repository;

/**
 * MotorshipRoomImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotorshipRoomImageRepository extends \Doctrine\ORM\EntityRepository
{
}
