<?php

namespace CruiseBundle\Repository;

/**
 * CompanionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanionRepository extends \Doctrine\ORM\EntityRepository
{
}
