<?php

namespace CruiseBundle\Repository;

/**
 * CruiseCruiseCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CruiseCruiseCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
