<?php

namespace CruiseBundle\Repository;

/**
 * CruiseDiscountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CruiseDiscountRepository extends \Doctrine\ORM\EntityRepository
{
}
