<?php

namespace CruiseBundle\Repository;

/**
 * CruiseCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CruiseCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
