<?php

namespace CruiseBundle\Repository;

/**
 * CruiseTariffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CruiseTariffRepository extends \Doctrine\ORM\EntityRepository
{
}
