<?php

namespace CruiseBundle\Repository;

/**
 * CruiseDaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CruiseDaysRepository extends \Doctrine\ORM\EntityRepository
{
}
