<?php

namespace CruiseBundle\Repository;

/**
 * CruiseRoomBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CruiseRoomBlockRepository extends \Doctrine\ORM\EntityRepository
{
}
