<?php

namespace CruiseBundle\Repository;

/**
 * CruiseRoomStatus2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CruiseRoomStatusRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function countFreeRoom($cruise)
	{
		//$em = $this->getManager('cruise');
		
		$sql = "
		SELECT COUNT(*) `count_free`
		FROM `cruise_room_status2` `crs_2`
		INNER JOIN (
		SELECT
			`crs_1`.`id` AS `id`,
			`crs_1`.`room_id` AS `room_id`,
			MAX(`crs_1`.`date`) AS `date`,
			`cruise`.`date_start` `cruise_start`,
			`cruise`.`date_stop` `cruise_stop`,
			`cruise`.`id` `cruise_id`
		   FROM
			`cruise_room_status2` `crs_1`
			LEFT JOIN `cruise` ON `cruise`.`id` = $cruise
			INNER JOIN `room` ON `room`.`motorship_id` = `cruise`.`motorship_id` AND `crs_1`.`room_id` = `room`.`id`
		   WHERE
			`crs_1`.`date` <= `cruise`.`date_start`
		   GROUP BY 
			`crs_1`.`room_id`
		) AS `date_start_max`	ON `date_start_max`.`date` = `crs_2`.`date` AND `date_start_max`.`room_id` = `crs_2`.`room_id`
		LEFT JOIN `room_status` ON `room_status`.`id` = `crs_2`.`status_id`
		LEFT JOIN (
			SELECT `cruise_room_status2`.`id` `id` , `cruise_room_status2`.`date` `date`, `room_status`.`reserve` `reserve`
			FROM `cruise_room_status2` 
			LEFT JOIN `room_status` ON `room_status`.`id` = `cruise_room_status2`.`status_id`
		) `crs_3`  ON `crs_3`.`id` = `date_start_max`.`id`  AND ( `crs_3`.`date` BETWEEN `date_start_max`.`cruise_start` AND `date_start_max`.`cruise_stop`  )
		LEFT JOIN `cruise_room_block` ON `crs_2`.`room_id` = `cruise_room_block`.`room_id` AND `cruise_room_block`.`cruise_id` = `date_start_max`.`cruise_id`
		WHERE  `cruise_room_block`.`id` IS NULL
		AND `crs_3`.`reserve` IS NULL 
		AND `room_status`.`reserve` = 0
		";
		$connection = $this->_em->getConnection();
		$statement = $connection->prepare($sql);
		$statement->execute();
		$result = $statement->fetchColumn();	
		
		return $result;
	}
	
	
	public function getFreeRooms($cruise)
	{
		$sql = "
		SELECT `crs_2`.`room_id` , 

		IF(`cruise_room_block`.`id` IS NULL , IF(`crs_3`.`reserve` IS NULL, `room_status`.`reserve`, 1 ) , 1) as `final_reserve`

		FROM `cruise_room_status2` `crs_2`

		INNER JOIN (

		SELECT
			`crs_1`.`id` AS `id`,
			`crs_1`.`room_id` AS `room_id`,
			MAX(`crs_1`.`date`) AS `date`,
			`cruise`.`date_start` `cruise_start`,
			`cruise`.`date_stop` `cruise_stop`,
			`cruise`.`id` `cruise_id`
		   FROM
			`cruise_room_status2` `crs_1`
			LEFT JOIN `cruise` ON `cruise`.`id` = $cruise
			
			INNER JOIN `room` ON `room`.`motorship_id` = `cruise`.`motorship_id` AND `crs_1`.`room_id` = `room`.`id`
			
			
		   WHERE
			`crs_1`.`date` <= `cruise`.`date_start`
		   
		   GROUP BY 
			`crs_1`.`room_id`
		) AS `date_start_max`	ON `date_start_max`.`date` = `crs_2`.`date` AND `date_start_max`.`room_id` = `crs_2`.`room_id`

		LEFT JOIN `room_status` ON `room_status`.`id` = `crs_2`.`status_id`

		LEFT JOIN (
			SELECT `cruise_room_status2`.`id` `id` , `cruise_room_status2`.`date` `date`, `room_status`.`reserve` `reserve`
			FROM `cruise_room_status2` 
			LEFT JOIN `room_status` ON `room_status`.`id` = `cruise_room_status2`.`status_id`
		) `crs_3`  ON `crs_3`.`id` = `date_start_max`.`id`  AND ( `crs_3`.`date` BETWEEN `date_start_max`.`cruise_start` AND `date_start_max`.`cruise_stop`  )


		LEFT JOIN `cruise_room_block` ON `crs_2`.`room_id` = `cruise_room_block`.`room_id` AND `cruise_room_block`.`cruise_id` = `date_start_max`.`cruise_id`
		";
		$connection = $this->_em->getConnection();
		$statement = $connection->prepare($sql);
		$statement->execute();
		$result = $statement->fetchAll();	
		
		return $result;		
	}

}
