<?php

namespace CruiseBundle\Repository;

/**
 * CruiseClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CruiseClassRepository extends \Doctrine\ORM\EntityRepository
{
}
