<?php

namespace CruiseBundle\Repository;

/**
 * DiscountDocumentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscountDocumentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
