<?php

namespace CruiseBundle\Repository;

/**
 * DiscountCompanionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscountCompanionRepository extends \Doctrine\ORM\EntityRepository
{
}
