<?php

namespace CruiseBundle\Repository;

/**
 * DiscountExclusionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscountExclusionRepository extends \Doctrine\ORM\EntityRepository
{
}
