<?php

namespace CruiseBundle\Repository;

/**
 * ExcursionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExcursionRepository extends \Doctrine\ORM\EntityRepository
{
}
