<?php

namespace CruiseBundle\Repository;

/**
 * MotorshipTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotorshipTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
