<?php

namespace CruiseBundle\Repository;

/**
 * MotorshipHallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotorshipHallRepository extends \Doctrine\ORM\EntityRepository
{
}
