<?php

namespace CruiseBundle\Repository;

/**
 * MotorshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotorshipRepository extends \Doctrine\ORM\EntityRepository
{
}
