<?php

namespace CruiseBundle\Repository;

/**
 * MotorshipRoomsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotorshipRoomsRepository extends \Doctrine\ORM\EntityRepository
{
}
