<?php

namespace CruiseBundle\Repository;

/**
 * MotorshipClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotorshipClassRepository extends \Doctrine\ORM\EntityRepository
{
}
