<?php

namespace CruiseBundle\Repository;

/**
 * OrderItemPlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemPlaceRepository extends \Doctrine\ORM\EntityRepository
{
}
