<?php

namespace CruiseBundle\Repository;

/**
 * OrderingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderingRepository extends \Doctrine\ORM\EntityRepository
{
}
