<?php

namespace CruiseBundle\Repository;

/**
 * OrderDiscountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDiscountRepository extends \Doctrine\ORM\EntityRepository
{
}
