<?php

namespace CruiseBundle\Repository;

/**
 * OrderDeleteStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDeleteStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
