<?php

namespace CruiseBundle\Repository;

/**
 * RoomStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
