<?php

namespace CruiseBundle\Repository;

/**
 * RoomPlacingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomPlacingRepository extends \Doctrine\ORM\EntityRepository
{
}
