<?php

namespace CruiseBundle\Repository;

/**
 * TariffDocumentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TariffDocumentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
