<?php

namespace CruiseBundle\Repository;

/**
 * TouristDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TouristDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
