<?php

namespace CruiseBundle\Repository;

/**
 * TouristRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TouristRepository extends \Doctrine\ORM\EntityRepository
{
}
