<?php

namespace CruiseBundle\Repository;

/**
 * TouristDocumentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TouristDocumentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
